export const launchpadAbi = [
  {
    type: 'constructor',
    inputs: [
      {name: 'tokenFactory', type: 'address', internalType: 'address'},
      {name: 'strategyFactory', type: 'address', internalType: 'address'},
      {name: 'ccaFactory', type: 'address', internalType: 'address'},
      {name: 'currency', type: 'address', internalType: 'address'},
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'ALL_HOOK_MASK',
    inputs: [],
    outputs: [{name: '', type: 'uint160', internalType: 'uint160'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'AUCTION_DURATION',
    inputs: [],
    outputs: [{name: '', type: 'uint64', internalType: 'uint64'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'CCA_FACTORY',
    inputs: [],
    outputs: [{name: '', type: 'address', internalType: 'address'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'CCA_TICK_SPACING',
    inputs: [],
    outputs: [{name: '', type: 'uint256', internalType: 'uint256'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'CLAIM_DELAY',
    inputs: [],
    outputs: [{name: '', type: 'uint64', internalType: 'uint64'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'CURRENCY',
    inputs: [],
    outputs: [{name: '', type: 'address', internalType: 'address'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'FLOOR_PRICE',
    inputs: [],
    outputs: [{name: '', type: 'uint256', internalType: 'uint256'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'MAX_CURRENCY_AMOUNT_FOR_LP',
    inputs: [],
    outputs: [{name: '', type: 'uint128', internalType: 'uint128'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'MIGRATION_DELAY',
    inputs: [],
    outputs: [{name: '', type: 'uint64', internalType: 'uint64'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'POOL_LP_FEE',
    inputs: [],
    outputs: [{name: '', type: 'uint24', internalType: 'uint24'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'POOL_TICK_SPACING',
    inputs: [],
    outputs: [{name: '', type: 'int24', internalType: 'int24'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'RECIPIENT',
    inputs: [],
    outputs: [{name: '', type: 'address', internalType: 'address'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'REQUIRED_CURRENCY_RAISED',
    inputs: [],
    outputs: [{name: '', type: 'uint128', internalType: 'uint128'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'REQUIRED_HOOK_FLAGS',
    inputs: [],
    outputs: [{name: '', type: 'uint160', internalType: 'uint160'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'STRATEGY_FACTORY',
    inputs: [],
    outputs: [{name: '', type: 'address', internalType: 'address'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'SWEEP_DELAY',
    inputs: [],
    outputs: [{name: '', type: 'uint64', internalType: 'uint64'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'TOKEN_DECIMALS',
    inputs: [],
    outputs: [{name: '', type: 'uint8', internalType: 'uint8'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'TOKEN_FACTORY',
    inputs: [],
    outputs: [{name: '', type: 'address', internalType: 'address'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'TOKEN_SPLIT',
    inputs: [],
    outputs: [{name: '', type: 'uint24', internalType: 'uint24'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'TOTAL_MPS',
    inputs: [],
    outputs: [{name: '', type: 'uint24', internalType: 'uint24'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'TOTAL_SUPPLY',
    inputs: [],
    outputs: [{name: '', type: 'uint128', internalType: 'uint128'}],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getStrategyConfig',
    inputs: [{name: 'startBlock', type: 'uint64', internalType: 'uint64'}],
    outputs: [
      {
        name: 'migratorParams',
        type: 'tuple',
        internalType: 'struct MigratorParameters',
        components: [
          {name: 'migrationBlock', type: 'uint64', internalType: 'uint64'},
          {name: 'currency', type: 'address', internalType: 'address'},
          {name: 'poolLPFee', type: 'uint24', internalType: 'uint24'},
          {name: 'poolTickSpacing', type: 'int24', internalType: 'int24'},
          {name: 'tokenSplit', type: 'uint24', internalType: 'uint24'},
          {
            name: 'initializerFactory',
            type: 'address',
            internalType: 'address',
          },
          {name: 'positionRecipient', type: 'address', internalType: 'address'},
          {name: 'sweepBlock', type: 'uint64', internalType: 'uint64'},
          {name: 'operator', type: 'address', internalType: 'address'},
          {
            name: 'maxCurrencyAmountForLP',
            type: 'uint128',
            internalType: 'uint128',
          },
        ],
      },
      {name: 'auctionParamsEncoded', type: 'bytes', internalType: 'bytes'},
      {name: 'tokenFactory', type: 'address', internalType: 'address'},
      {name: 'strategyFactory', type: 'address', internalType: 'address'},
      {name: 'ccaFactory', type: 'address', internalType: 'address'},
      {name: 'currency', type: 'address', internalType: 'address'},
      {
        name: 'positionManager',
        type: 'address',
        internalType: 'contract IPositionManager',
      },
      {
        name: 'poolManager',
        type: 'address',
        internalType: 'contract IPoolManager',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'launch',
    inputs: [
      {
        name: 'tokenParams',
        type: 'tuple',
        internalType: 'struct Launchpad.TokenParams',
        components: [
          {name: 'name', type: 'string', internalType: 'string'},
          {name: 'symbol', type: 'string', internalType: 'string'},
          {
            name: 'metadata',
            type: 'tuple',
            internalType: 'struct UERC20Metadata',
            components: [
              {name: 'description', type: 'string', internalType: 'string'},
              {name: 'website', type: 'string', internalType: 'string'},
              {name: 'image', type: 'string', internalType: 'string'},
            ],
          },
        ],
      },
      {name: 'startBlock', type: 'uint64', internalType: 'uint64'},
      {name: 'salt', type: 'bytes32', internalType: 'bytes32'},
    ],
    outputs: [
      {name: 'token', type: 'address', internalType: 'address'},
      {name: 'strategy', type: 'address', internalType: 'address'},
      {name: 'auction', type: 'address', internalType: 'address'},
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'event',
    name: 'TokenLaunched',
    inputs: [
      {name: 'token', type: 'address', indexed: true, internalType: 'address'},
      {
        name: 'strategy',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'auction',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'creator',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
      {name: 'name', type: 'string', indexed: false, internalType: 'string'},
      {name: 'symbol', type: 'string', indexed: false, internalType: 'string'},
    ],
    anonymous: false,
  },
  {
    type: 'error',
    name: 'InvalidStepsDataDuration',
    inputs: [
      {name: 'actual', type: 'uint64', internalType: 'uint64'},
      {name: 'expected', type: 'uint64', internalType: 'uint64'},
    ],
  },
  {
    type: 'error',
    name: 'InvalidStepsDataMps',
    inputs: [
      {name: 'actual', type: 'uint256', internalType: 'uint256'},
      {name: 'expected', type: 'uint256', internalType: 'uint256'},
    ],
  },
  {type: 'error', name: 'ReentrancyGuardReentrantCall', inputs: []},
  {
    type: 'error',
    name: 'SafeERC20FailedOperation',
    inputs: [{name: 'token', type: 'address', internalType: 'address'}],
  },
] as const;
