export const launchpadLensAbi = [
  {
    type: 'function',
    name: 'getAuctionState',
    inputs: [{name: 'auction', type: 'address', internalType: 'address'}],
    outputs: [
      {
        name: 'state',
        type: 'tuple',
        internalType: 'struct LaunchpadLens.AuctionState',
        components: [
          {name: 'clearingPriceQ96', type: 'uint256', internalType: 'uint256'},
          {name: 'currencyRaised', type: 'uint256', internalType: 'uint256'},
          {name: 'totalBidAmount', type: 'uint256', internalType: 'uint256'},
          {name: 'totalCleared', type: 'uint256', internalType: 'uint256'},
          {name: 'startBlock', type: 'uint64', internalType: 'uint64'},
          {name: 'endBlock', type: 'uint64', internalType: 'uint64'},
          {name: 'claimBlock', type: 'uint64', internalType: 'uint64'},
          {name: 'floorPriceQ96', type: 'uint256', internalType: 'uint256'},
          {name: 'tickSpacingQ96', type: 'uint256', internalType: 'uint256'},
          {name: 'token', type: 'address', internalType: 'address'},
          {name: 'currency', type: 'address', internalType: 'address'},
          {name: 'totalSupply', type: 'uint128', internalType: 'uint128'},
          {name: 'tokenDecimals', type: 'uint8', internalType: 'uint8'},
          {name: 'currencyDecimals', type: 'uint8', internalType: 'uint8'},
          {name: 'status', type: 'uint8', internalType: 'uint8'},
          {name: 'progress', type: 'uint8', internalType: 'uint8'},
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getBids',
    inputs: [
      {name: 'auction', type: 'address', internalType: 'address'},
      {name: 'bidIds', type: 'uint256[]', internalType: 'uint256[]'},
    ],
    outputs: [
      {
        name: 'bids',
        type: 'tuple[]',
        internalType: 'struct LaunchpadLens.BidWithId[]',
        components: [
          {name: 'id', type: 'uint256', internalType: 'uint256'},
          {name: 'startBlock', type: 'uint64', internalType: 'uint64'},
          {name: 'startCumulativeMps', type: 'uint24', internalType: 'uint24'},
          {name: 'exitedBlock', type: 'uint64', internalType: 'uint64'},
          {name: 'maxPrice', type: 'uint256', internalType: 'uint256'},
          {name: 'owner', type: 'address', internalType: 'address'},
          {name: 'amountQ96', type: 'uint256', internalType: 'uint256'},
          {name: 'tokensFilled', type: 'uint256', internalType: 'uint256'},
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getPoolKeyAndMigrationStatus',
    inputs: [{name: 'strategy', type: 'address', internalType: 'address'}],
    outputs: [
      {
        name: 'result',
        type: 'tuple',
        internalType: 'struct LaunchpadLens.PoolKeyWithStatus',
        components: [
          {name: 'currency0', type: 'address', internalType: 'address'},
          {name: 'currency1', type: 'address', internalType: 'address'},
          {name: 'fee', type: 'uint24', internalType: 'uint24'},
          {name: 'tickSpacing', type: 'int24', internalType: 'int24'},
          {name: 'hooks', type: 'address', internalType: 'address'},
          {name: 'isMigrated', type: 'bool', internalType: 'bool'},
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getStrategyState',
    inputs: [{name: 'strategy', type: 'address', internalType: 'address'}],
    outputs: [
      {
        name: 'result',
        type: 'tuple',
        internalType: 'struct LaunchpadLens.StrategyState',
        components: [
          {name: 'currency0', type: 'address', internalType: 'address'},
          {name: 'currency1', type: 'address', internalType: 'address'},
          {name: 'fee', type: 'uint24', internalType: 'uint24'},
          {name: 'tickSpacing', type: 'int24', internalType: 'int24'},
          {name: 'hooks', type: 'address', internalType: 'address'},
          {name: 'isMigrated', type: 'bool', internalType: 'bool'},
          {name: 'token', type: 'address', internalType: 'address'},
          {name: 'currency', type: 'address', internalType: 'address'},
          {name: 'migrationBlock', type: 'uint64', internalType: 'uint64'},
          {name: 'initializer', type: 'address', internalType: 'address'},
          {name: 'poolManager', type: 'address', internalType: 'address'},
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getTokenData',
    inputs: [{name: 'token', type: 'address', internalType: 'address'}],
    outputs: [
      {
        name: 'data',
        type: 'tuple',
        internalType: 'struct LaunchpadLens.TokenData',
        components: [
          {name: 'name', type: 'string', internalType: 'string'},
          {name: 'symbol', type: 'string', internalType: 'string'},
          {name: 'decimals', type: 'uint8', internalType: 'uint8'},
          {name: 'totalSupply', type: 'uint256', internalType: 'uint256'},
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getPoolPrice',
    inputs: [
      {
        name: 'poolManager',
        type: 'address',
        internalType: 'contract IPoolManager',
      },
      {
        name: 'poolKey',
        type: 'tuple',
        internalType: 'struct PoolKey',
        components: [
          {name: 'currency0', type: 'address', internalType: 'Currency'},
          {name: 'currency1', type: 'address', internalType: 'Currency'},
          {name: 'fee', type: 'uint24', internalType: 'uint24'},
          {name: 'tickSpacing', type: 'int24', internalType: 'int24'},
          {name: 'hooks', type: 'address', internalType: 'contract IHooks'},
        ],
      },
    ],
    outputs: [
      {
        name: 'result',
        type: 'tuple',
        internalType: 'struct LaunchpadLens.PoolPrice',
        components: [
          {name: 'tick', type: 'int24', internalType: 'int24'},
          {name: 'sqrtPriceX96', type: 'uint160', internalType: 'uint160'},
          {name: 'priceE18', type: 'uint256', internalType: 'uint256'},
        ],
      },
    ],
    stateMutability: 'view',
  },
] as const;
